### ISSUE TITLE
Merger Config

### ISSUE THREAD

**Issue by mihaibivol** [inspirehep/json-merger#18]
We need to build a basic config for all the list fields inside the HEP schema.
So far we have:
- Custom comparator for author names.
- Configurable comparator which works by comparing various fields in an element. We can configure it like this:

> These objects are equal if `(field1 in first obj is equal to field1 in second obj AND field2 in first obj is equal to field2 in second obj) OR (field3 in first obj is equal to field3 in second obj)`. This also accepts custom normalization functions for each of the fields.

Also for each field we want to decide either we 

Such configuration looks like this `[['field1', 'field2'], 'field3']`.

The lists fields that need configuraturation are:
- [x] `authors` - **keep only one** - **Done** via name edit distance magic (see `contrib.inspirehep`)
  - [x] `authors.affiliations` - **do union** -  Merge by `value` field :white_check_mark: 
  - [ ] `authors.other_ids` - **do union** - Merge by `source` field :white_check_mark: 
  - [ ] `contributor_roles` - **do_union** - Merge by `value` field :white_check_mark: 
- [ ] `funding_info` - **do union** - Compare using record equality :white_check_mark: 
- [ ] `isbns` - **do union** - Merge by `value` field :white_check_mark: 
- [ ] `report_numbers` - **do union** - Compare using record equality :white_check_mark: 
- [x] `public_notes` - **do union** - Compare using record equality :white_check_mark: 
- [ ] `abstracts` - **do union** - Compare by `source` :white_check_mark: 
- [ ] `spires_synos` - **do union** - Compare using record equality :white_check_mark: 
- [ ] `imprints` - **do union** - Compare using record equality :white_check_mark: 
- [ ] `titles` / `titles_old` / `title_variations` / `title_translations` - **do union** - Compare using record equality **???** (or maybe `source`) -- (really, really, what on earth is this? @jacquerie I get your frustration) - inspirehep/inspire-next#1257
- [ ] `edition` - **do union??** - Compare using record equality (?? don't know what this is) inspirehep/inspire-next#1258
- [ ] `thesis_supervisor` - **do union??** - Same as authors inspirehep/inspire-next#1259
- [ ] `thesis` - **Change to regular field** inspirehep/inspire-next/issues/1260
  - [ ] `thesis.institutions` - **do union** - Compare by `name` or `record.$ref` (this way we can add the reference automatically) :white_check_mark: 
- [ ] `hidden_notes` -  **do union** - Compare using record equality :white_check_mark: 
- [ ] `publication_info` - **do union** - Lots of OR configs (so far only for `journal_`)
  - [ ] `publication_info.cnum` - **??** inspirehep/inspire-next#1261
- [ ] `copyright` - **do union** - Compare using record equality **???** (or maybe something else)
- [ ] `references` - **keep only one** - **here be many dragons, but at least we do not merge**
  - [ ] `references.publisher`
  - [ ] `references.report_number` union them (amend schema to consider arxiv reportnumber as special)
  - [ ] `references.url` union them
  - [ ] `references.collaboration` union them
  - [ ] `references.title` TODO issue (we need only one, the schema must be corrected)
  - [ ] `references.misc` union them.
  - [ ] `references.editors` take from the one that has it
  - [ ] `references.raw_reference`union them (they are good for correcting)
  - [ ] `references.authors` should be used for matching with e.g. title in a fuzzy way, whatever that means. then take from the one that has it
  - [ ] `references.journal_pubnote`: ha! this should be split it's a comma separated list of information: journal_title,journal_volume,(journal_issue,)journal_firstpage(journal_lastpage)|artid (there's a util for split and guessing artid/first_page)
  - Here we need to keep by default references from only one side and show in conflicts the non matched ones. inspirehep/inspire-next#430
- [ ] `thesaurus_terms` - **do union** - Compare using record equality :white_check_mark: 
- [ ] `accelerator_experiments` - **do union** - Probably use some OR fields (or maybe record equality) (match by `experiment`, then by `record.$ref`) :white_check_mark: 
- [ ] `arxiv_eprints` - **do union** - Compare using `value` :white_check_mark: 
  - [ ] `arxiv_eprints.categories`  - **do union** (only strings) :white_check_mark: 
- [ ] `free_keywords` - **do union** :white_check_mark: 
- [ ] `book_series` - **do union** (just merge by record equality) :white_check_mark: 
- [ ] `oai_pmh` - **do union** - might be deprecated
- [ ] `collaboration` - **do union** - either by `value` or `record` :white_check_mark: 
- [ ] `classification_number` - **do union** - Compare using record equality
- [ ] `dois` - **do union** - Match by `.value`
- [ ] `document_type` - **do union** - Compare using record equality
- [x] `collections` - **do union** Compare using the `primary` field
- [ ] `deleted_records` - **do union** Compare using record equality (or `$ref` it's the same thing)
- [ ] `license` - **do union??** Compare using record equality or (`url` field)
- [ ] `languages` - **do union** Compare using record equality
- [ ] `page_nr` - Should this ever be a list?
- [x] `urls` - **do union** compare by `url` field
- [ ] `corporate_author` - **do union** compare by record equality or author names (since we already have them)
- [x] `external_system_numbers` - **do union** compare by `institute` field
- [ ] `persistent_identifiers` - **do union** compare by (`source` - `value`)

**Comment by mihaibivol** [comment]
@kaplun So, it has come to this. Seems that union should be the default (rather than override with entities from one list)

This is the current "blocker" issue :)

**Comment by kaplun** [comment]
General rule: if merging arXiv and publisher, the publisher version takes precedence, so for lists, we take the entities in publisher and merge in those from arXiv.

**Comment by kaplun** [comment]
What's the status of this one?

**Comment by mihaibivol** [comment]
Probably dead. There's no need to write a valid config that will be invalidated at the first model change.

I'd better set up an instance of `merger.inspirehep.net` on a machine that is not mine since now one can play with the configuration of `union` vs `keep only head things` vs `keep only update things`

**Comment by mihaibivol** [comment]
This should be a simple task after I have documented the usage of the module.

**Comment by kaplun** [comment]
Ok. So let's declared superseded by #20

**Comment by kaplun** [comment]
> Probably dead. There's no need to write a valid config that will be invalidated at the first model change.

However I wouldn't be so dramatic. It's not that we are amending the model for fun up-side-down. We are just adjusting it when clear improvements are spot.

So even if a config is not fully up-to-date will be easily adjusted.

**Comment by mihaibivol** [comment]
If anything happens to me the starting point of #20 are acceptance tests :))

**Comment by mihaibivol** [comment]
The optimistic final status is:
- merger.inspirehep.net can always be used for picking defaults (keep_head, keep_update, union)
- all off the fields should be comparable by using existing classes
